sudo: required
dist: trusty

language: ruby

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_4.gemfile
  - gemfiles/spree_master.gemfile

rvm:
  - 2.2.7
  - 2.3.1
  - 2.4.0

before_install:
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
